// Creado — shape of a URL entity in the system
// This is a pure TypeScript type — no database, no framework
export interface Url {
  // Unique identifier (auto-generated by the DB)
  id: string;

  // The original long URL the user submitted
  originalUrl: string;

  // The short code we generated (e.g. "aB3xKp2")
  shortCode: string;

  // How many times this short link has been visited
  clicks: number;

  // When this short URL was created
  createdAt: Date;
}
